### ISSUE TITLE
Automate the deployment of Firefox web extension

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#205]
## Firefox
> You can upload a new version for signing by issuing a `PUT` request and including the contents of your add-on in the upload parameter as multi-part formdata. This will create a pending version on the add-on and will prevent future submissions to this version unless validation or review fails.

http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version

**Comment by bfred-it** [comment]
For reference, this is how we've done it for npmhub:

- [.travis.yml](https://github.com/npmhub/npmhub/blob/0b3040a212027cc4fd4910a98ee0e478633480ef/.travis.yml#L6-L13)
    
    ```yml
    env:
      - EXTENSION_ID=kbbbjimdjbjclaebffknlabpogocablj
    deploy:
      provider: script
      skip_cleanup: true
      script: npm run update-version; npm run release-cws; npm run release-amo
      on:
          branch: master
    ```

- [package.json](https://github.com/npmhub/npmhub/blob/0b3040a212027cc4fd4910a98ee0e478633480ef/package.json#L16-L18)

    ```json
    {
        "scripts": {
          "test": "xo && web-ext lint",
          "release-amo": "OK='Your add-on has been submitted for review.'; web-ext sign -s extension | sed -n \"s/\\($OK\\).*$/\\1/;1,/$OK/p\" | perl -pe 'BEGIN { $s=1 } END { exit $s } $s=0 if /'\"$OK\"'/;'",
          "release-cws": "webstore upload --source=extension --auto-publish",
          "update-version": "dot-json extension/manifest.json version $(date -u +%Y.%-m.%-d.%-H%M)"
        }
    }
    ```
