### ISSUE TITLE
Installation either without docker or without nginx and postgres

### ISSUE THREAD

**Issue by sinni800** [lesspass/lesspass#283]
Not everyone has a server or so many resources to dedicate (or are on a VPS), so I would suggest a way to use another postgres instance/container already existing, plus not install Nginx (and listen on a random high port for a manual proxy pass). Alternatively, just create an install document for classic installation.

I havent done much with docker so if this is already possible our of the box, I apologize

**Comment by guillaumevincent** [comment]
Hello,

> Not everyone has a server or so many resources to dedicate

LessPass Database is free. Self-hosted solutions are always more expensive. You need your own hardware.

Another solution is to learn more about docker and create a docker-compose file that fit your need.
See existing `docker-compose.prod.yml` for some help.

Something like that (:warning: not tested):

Create a `docker-compose.yml` file

```
version: '2'
services:
  backend:
    restart: always
    image: lesspass/backend:latest
    expose:
      - '8000'
    volumes:
      - www:/backend/www
    links:
      - db
    env_file:
      - .env
    environment:
      DATABASE_ENGINE: 'django.db.backends.postgresql'
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
  frontend:
    restart: always
    image: lesspass/frontend:latest
    expose:
      - '<YOUR_PORT>:8080'
volumes:
  www:
```

Change DATABASE_NAME, DATABASE_USER, DATABASE_HOST, DATABASE_PORT, YOUR_PORT to fit your need.

and then `docker-compose up -d`
