### ISSUE TITLE
Backend: 500 Internal Server Error

### ISSUE THREAD

**Issue by Commifreak** [lesspass/lesspass#330]
Hi,

since a few days, LessPass stopped working without anything touched?

frontend is working but all api calls end in 500:

```
POST /api/tokens/auth/ HTTP/1.1
Host: lesspass.kluthr.de
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://lesspass.kluthr.de/
Content-Type: application/json;charset=utf-8
Content-Length: 60
Connection: keep-alive
```

```
HTTP/1.1 500 Internal Server Error
Date: Fri, 18 May 2018 13:12:29 GMT
Server: nginx
Strict-Transport-Security: max-age=0
Content-Type: text/html
Content-Length: 141
Connection: close
```

```
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

nginx seems to do it's thing right, but the backend service seem to have a problem. How to check further things? Iam on latest images, based on:

```
version: '2'
services:
  db:
    restart: always
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  backend:
    restart: always
    image: lesspass/backend:latest
    expose:
      - '8000'
    volumes:
      - www:/backend/www
    links:
      - db
    env_file:
      - .env
    environment:
      DATABASE_ENGINE: 'django.db.backends.postgresql'
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
  frontend:
    restart: always
    image: lesspass/frontend:latest
  nginx:
    restart: always
    image: lesspass/nginx:latest
    ports:
      - '127.0.0.1:9292:80'
      - '127.0.0.1:9393:443'
    volumes_from:
      - backend
    volumes:
      - ./ssl:/certificates
    links:
      - backend
      - frontend
    environment:
      - DOMAIN=${DOMAIN}
volumes:
  postgresql:
  www:
```

Thanks in advance ;)
