### ISSUE TITLE
backend_1   | nc: getaddrinfo: Name does not resolve Trying to use external postgres server

### ISSUE THREAD

**Issue by robp2175** [lesspass/lesspass#421]
I am trying to use an external postgres server, but I keep getting nc: getaddrinfo: Name does not resolve when I startup the containers. My compose file is below and my env file. 
```
version: '2'
services:
  backend:
    restart: always
    image: lesspass/backend:latest
    expose:
      - '8114'
    volumes:
      - www:/backend/www
    env_file:
      - .env
    environment:
      DATABASE_ENGINE: 'django.db.backends.postgresql'
      DATABASE_NAME: 'lesspass'
      DATABASE_USER: 'lesspass'
      DATABASE_HOST: '10.40.100.65'
      DATABASE_PORT: '5432'
  frontend:
    restart: always
    image: lesspass/frontend:latest
volumes:
  www:

```

```
SECRET_KEY=azertyuiopqsdfghjklmwxcvbn123456
DATABASE_ENGINE=django.db.backends.postgresql
DATABASE_NAME=lesspass
DATABASE_USER=lesspass
DATABASE_PASSWORD=password
DATABASE_HOST=10.40.100.65
DATABASE_PORT=5432
FQDN=localhost
DEBUG=1
```
