### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [lesspass/lesspass#564]
Ref: https://f-droid.org/wiki/index.php?title=com.lesspass.android/lastbuild_90109&oldid=280132

**Comment by guillaumevincent** [comment]
Thank you for reporting this

So the minimal version of node available for FDroid is 8. Node 8 is not supported any more. Version 10 is in maintenance mode.
See https://nodejs.org/en/about/releases/

Maybe we should raise the issue on FDroid side.

Let me check where this module is needed

**Comment by licaon-kter** [comment]
You can always bring your own, see how other apps do it, eg:
```
    sudo:
      - curl -Lo node.tar.xz https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.xz
      - echo "1956e196e3c3c8ef5f0c45db76d7c1245af4ccdda2b7ab30a57ce91d6e165caa node.tar.xz"
        | sha256sum -c -
      - tar xJf node.tar.xz
      - cp -a node-v12.16.3-linux-x64/. /usr/local/
      - npm -g install yarn
    init: yarn install
```

Which version do you need exactly?

**Comment by guillaumevincent** [comment]
prettier need at least version 10
latest LTS (version 12) will be ok

**Comment by licaon-kter** [comment]
@Lurux taking a look now

**Comment by Lurux** [comment]
Sorry, I just realized this issue was about a previous version, and had been fixed for 9.3.0.

I remembered seeing an issue about F-Droid previously, hence why I jumped in here, thinking the fix may have failed to work. Should've created a new issue !

**Comment by licaon-kter** [comment]
It's not on autoupdate so it's always behind unless you/me/others fix it.

**Comment by licaon-kter** [comment]
We can look at these: https://github.com/lesspass/lesspass/blob/mobile-v9.7.0/mobile/android/app/build.gradle#L146-L147 but not execute functions, we need it to be static.

That being said... looking at the newest code maybe we can enable autoupdates in the next release: https://github.com/lesspass/lesspass/blob/565e68af7d1ac7d49f610af2f179aa830206147d/mobile/android/app/build.gradle#L150-L151

**Comment by Lurux** [comment]
If i understand correctly we need to hook this into their build system so they can detect and build new versions, is that correct ?

**Comment by licaon-kter** [comment]
No, F-Droid has a bot (well some scripts that run on schedule) that checks for new releases. If a new one is out it tries to pickup the version and add a new build block so later it is built by F-Droid.

**Comment by Lurux** [comment]
Ok so I assume the script could detect new versions if the info you highlighted above was static (?)

Anyways, I looked at the [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9928) mentioned previously to see if I can update manually in the meantime, but I have no idea if the build instructions are still valid, so I prefer to let someone who actually know the project to do that at some point. Maybe i could get the info from the build;gradle, but I don't have the time to learn this tool right now :sweat_smile: 

Should I open a new issue for this ?

**Comment by licaon-kter** [comment]
I tried once but I see we hit a known and recent react-native bug. Will update and retry the recipe with some fixes.

**Comment by licaon-kter** [comment]
Straight update to `mobile-9.7.0`:
```
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-manifest, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /home/vagrant/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar.
         > Java heap space
```

That sounded like a known issue https://github.com/facebook/react-native/issues/35210

So I tried to apply a known fix (last 4 lines in `prebuild:`):
```
  - versionName: 9.7.0
    versionCode: 90700
    commit: edaee40a0bd17747e35b8a4f75ed593313673ecc
    subdir: mobile/android/app/
    sudo:
      - sysctl fs.inotify.max_user_watches=524288 || true
      - curl -Lo node.tar.gz https://nodejs.org/dist/v14.21.1/node-v14.21.1-linux-x64.tar.gz
      - echo "8ae854dac7fa5e7dfd5dae8fe8e001c0599821705f650b32c4819149cfda1d0e  node.tar.gz"
        | sha256sum -c -
      - tar xzf node.tar.gz --strip-components=1 -C /usr/local/
      - npm -g install yarn
    init: yarn install
    gradle:
      - yes
    rm:
      - mobile/node_modules/react-native/template/android/build.gradle
    prebuild:
      - sed -i -e 's#../package.json#../../package.json#' ../build.gradle
      - sed -i -e '/enable enableSeparateBuildPerCPUArchitecture/d' build.gradle
      - sed -i -e '/enableHermes/s/true/false/' build.gradle
      - find ../.. -iname "build.gradle" -exec sed -i -e 's/react:react-native:+/react:react-native:0.66.5/'
        {} \;
      - sed -i -e 's/${_reactNativeVersion}/0.66.5/' ../../node_modules/react-native-touch-id/android/build.gradle
      - sed -i -e 's/ "0.66.0/ "0.66.5/' ../../package.json
      - sed -i -e 's/native@0.66.0/native@0.66.5/' -e 's/version "0.66.0"/version
        "0.66.5"/' -e 's/native-0.66.0.tgz.*"/native-0.66.5.tgz"/' -e 's!sha512-m26TK.*!sha512-dC5xmE1anT+m8eGU0N/gv2XUWZygii6TTqbwZPsN+uMhVvjxt4FsTqpZOFFvA5sxLPR/NDEz8uybTvItNBMClw==!'
        ../../yarn.lock
    scanignore:
      - mobile/android/build.gradle
      - mobile/node_modules/react-native/android/com/facebook/react/react-native
      - mobile/node_modules/jsc-android/dist/org/webkit/android-jsc
      - mobile/node_modules/react-native-screens/android/build.gradle
      - mobile/node_modules/@react-native-community/async-storage/android/build.gradle
      - mobile/node_modules/react-native-vector-icons/android/build.gradle
      - mobile/node_modules/@react-native-community/masked-view/android/build.gradle
      - mobile/node_modules/react-native-safe-area-context/android/build.gradle
    scandelete:
      - mobile/node_modules/
    ndk: r21e
```

But that fails with `Could not find com.facebook.react:react-native:0.66.5` and looking at https://mvnrepository.com/artifact/com.facebook.react/react-native that might be true

Any thoughts?
